//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroup
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ProductCategoryID { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
